package com.core.appservices.serializers;

public enum Serializers {
    // JSON
    JSON_CLIENT,
    JSON_CAST_CLIENT,
    JSON_BOOK,
    JSON_CAST_BOOK,
    JSON_ORDER,
    JSON_CAST_ORDER,
    JSON_COURSES,
    JSON_CAST_COURSES,
    JSON_EMPLOYEE,
    JSON_CAST_EMPLOYEE,
    // XML
    XML_CLIENT,
    XML_CAST_CLIENT,
    XML_BOOK,
    XML_CAST_BOOK,
    XML_ORDER,
    XML_CAST_ORDER,
    XML_COURSES,
    XML_CAST_COURSES,
    XML_EMPLOYEE,
    XML_CAST_EMPLOYEE
}
